"use client";
import {useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import type {OrchestratorToClientEvent} from "../../../orchestrator/src/types";

const WS_URL=process.env.NEXT_PUBLIC_ORCH_WS_URL??"ws://localhost:8787";
const labels:Record<string,string>={opening_safety:"Opening & Safety",grounding_consent:"Grounding & Consent",narrative:"Incident Narrative",structured_gathering:"Structured Data",evidence:"Photo & Evidence",review:"Review",output_generation:"Generate Report",closing:"Next Steps"};
const photoLabels:Record<string,string>={plate:"license plate",damage:"vehicle damage",scene:"accident scene",insurance_card:"insurance card"};

type Transcript={speaker:"user"|"agent";text:string};
type Completeness={missingRequired:string[];flaggedGaps:string[];isReportEligible:boolean;groupSummary?:Record<string,unknown>};

function base64ToBytes(b64:string){const bin=atob(b64);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function bytesToBase64(bytes:Uint8Array){let s="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(s)}

export default function CallPage(){
 const params=useSearchParams();const sessionId=params.get("session");
 const wsRef=useRef<WebSocket|null>(null);const audioCtxRef=useRef<AudioContext|null>(null);const streamRef=useRef<MediaStream|null>(null);const sourceRef=useRef<MediaStreamAudioSourceNode|null>(null);const workletRef=useRef<AudioWorkletNode|null>(null);const nextPlayRef=useRef(0);const partialRef=useRef("");
 const[connected,setConnected]=useState(false);const[recording,setRecording]=useState(false);const[muted,setMuted]=useState(false);const[phase,setPhase]=useState("opening_safety");const[complete,setComplete]=useState<Completeness|null>(null);const[transcripts,setTranscripts]=useState<Transcript[]>([]);const[partial,setPartial]=useState("");const[error,setError]=useState("");const[photo,setPhoto]=useState("");const[reportUrl,setReportUrl]=useState("");

 function playPcm(b64:string){const ctx=audioCtxRef.current;if(!ctx)return;const bytes=base64ToBytes(b64);const pcm=new Int16Array(bytes.buffer);const buf=ctx.createBuffer(1,pcm.length,24000);const ch=buf.getChannelData(0);for(let i=0;i<pcm.length;i++)ch[i]=pcm[i]/32768;const src=ctx.createBufferSource();src.buffer=buf;src.connect(ctx.destination);const start=Math.max(ctx.currentTime+0.02,nextPlayRef.current);src.start(start);nextPlayRef.current=start+buf.duration}
 async function startMic(){
   if(recording||!wsRef.current)return;
   const ws=wsRef.current;const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;
   const ctx=new AudioContext();audioCtxRef.current=ctx;await ctx.audioWorklet.addModule(URL.createObjectURL(new Blob([`class RecorderProcessor extends AudioWorkletProcessor{process(inputs){const input=inputs[0]&&inputs[0][0];if(!input)return true;const ratio=sampleRate/24000;const len=Math.floor(input.length/ratio);const pcm=new Int16Array(len);for(let i=0;i<len;i++){const x=Math.min(input.length-1,Math.floor(i*ratio));let v=input[x];v=Math.max(-1,Math.min(1,v));pcm[i]=v<0?v*32768:v*32767}this.port.postMessage(pcm.buffer,[pcm.buffer]);return true}}registerProcessor('insuranos-recorder',RecorderProcessor)`],{type:"application/javascript"})));
   const source=ctx.createMediaStreamSource(stream);const worklet=new AudioWorkletNode(ctx,"insuranos-recorder");worklet.port.onmessage=e=>{if(!muted&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"audio_chunk",audio:bytesToBase64(new Uint8Array(e.data))}))};source.connect(worklet);workletRef.current=worklet;sourceRef.current=source;setRecording(true);await ctx.resume();
 }
 function stopMic(){workletRef.current?.disconnect();sourceRef.current?.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());audioCtxRef.current?.close();workletRef.current=null;sourceRef.current=null;streamRef.current=null;setRecording(false)}
 async function uploadPhoto(file:File){if(!sessionId||!photo)return;const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});const res=await fetch("/api/photos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId,photo_type:photo,data_url:dataUrl})});const j=await res.json();if(!res.ok)throw new Error(j.error??"Photo upload failed");wsRef.current?.send(JSON.stringify({type:"photo_uploaded",photo_type:photo,storage_path:j.storage_path}));setPhoto("")}

 useEffect(()=>{if(!sessionId)return;const ws=new WebSocket(`${WS_URL.replace(/\/$/,"")}?session_id=${encodeURIComponent(sessionId)}`);wsRef.current=ws;ws.onopen=()=>setConnected(true);ws.onclose=()=>{setConnected(false);stopMic()};ws.onerror=()=>setError("Voice connection failed. Check the orchestrator URL and deployment.");ws.onmessage=e=>{let msg:OrchestratorToClientEvent;try{msg=JSON.parse(e.data)}catch{return}switch(msg.type){case"phase_update":setPhase(msg.phase);break;case"completeness_update":setComplete(msg.completeness as any);break;case"transcript_partial":if(msg.speaker==="user"){partialRef.current=msg.text;setPartial(msg.text)}break;case"transcript_final":setTranscripts(t=>[...t,{speaker:msg.speaker,text:msg.text}]);if(msg.speaker==="user"){partialRef.current="";setPartial("")}break;case"audio_out":playPcm(msg.audio);break;case"photo_requested":setPhoto(msg.photo_type);break;case"report_ready":setReportUrl(msg.report_url);break;case"error":setError(msg.message);break}};return()=>{ws.close();stopMic()}},[sessionId]);

 if(!sessionId)return <main className="p-8">Missing session.</main>;
 const progress=Math.min(100,Math.max(12,(Object.keys(labels).indexOf(phase)+1)*12.5));
 return <main className="min-h-screen px-4 py-6 md:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">INSURANOS</p><h1 className="mt-1 text-2xl font-bold">Accident claim session</h1></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${connected?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{connected?"Connected":"Connecting…"}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-slate-900 transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-sm text-slate-500">{labels[phase]??phase}</p>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_330px]"><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex min-h-[390px] flex-col"><div className="flex-1 space-y-4 overflow-auto"><div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">Keep your phone with you. The agent will ask one thing at a time. If you are in danger or anyone is hurt, contact emergency services first.</div>{transcripts.map((t,i)=><div key={i} className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm ${t.speaker==="agent"?"bg-slate-900 text-white":"bg-slate-100 text-slate-800 ml-auto"}`}><span className="mr-2 text-[11px] font-semibold uppercase opacity-60">{t.speaker}</span>{t.text}</div>)}{partial&&<div className="max-w-[88%] ml-auto rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-600">{partial}</div>}</div><div className="mt-5 flex flex-wrap items-center justify-center gap-3 border-t pt-5"><button onClick={recording?stopMic:startMic} disabled={!connected} className={`rounded-2xl px-7 py-4 font-semibold text-white ${recording?"bg-red-600":"bg-slate-900"}`}>{recording?"Stop microphone":"Start microphone"}</button><button onClick={()=>setMuted(m=>!m)} disabled={!recording} className="rounded-2xl border px-5 py-4 font-semibold disabled:opacity-40">{muted?"Unmute":"Mute"}</button><button onClick={()=>wsRef.current?.send(JSON.stringify({type:"client_event",event:"end_call"}))} className="rounded-2xl border border-slate-300 px-5 py-4 font-semibold">End</button></div></div></section>
 <aside className="space-y-4"><section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Claim completeness</h2>{complete?<><div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Required items remaining</p><p className="mt-1 text-3xl font-bold">{complete.missingRequired.length}</p></div><div className="mt-4"><p className="text-xs font-semibold uppercase tracking-widest text-slate-400">Next gaps</p><div className="mt-2 space-y-2">{complete.missingRequired.slice(0,5).map(x=><div key={x} className="rounded-xl border px-3 py-2 text-xs">{x}</div>)}</div></div></>:<p className="mt-3 text-sm text-slate-500">Waiting for server state…</p>}</section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Evidence</h2>{photo?<div className="mt-4 rounded-2xl border border-dashed p-4"><p className="text-sm">Agent requested a <strong>{photoLabels[photo]??photo}</strong> photo.</p><input className="mt-4 block w-full text-sm" type="file" accept="image/*" capture="environment" onChange={e=>{const f=e.target.files?.[0];if(f)uploadPhoto(f).catch(err=>setError(err.message))}}/><p className="mt-2 text-xs text-slate-400">Only capture it if it is safe to do so.</p></div>:<p className="mt-3 text-sm text-slate-500">No photo request right now.</p>}</section>
 {reportUrl&&<section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Report ready</h2><p className="mt-2 text-sm text-slate-500">Your insurer-ready report has been generated.</p><a className="mt-4 block rounded-xl bg-slate-900 px-4 py-3 text-center text-sm font-semibold text-white" href={reportUrl} target="_blank" rel="noreferrer">Open PDF report</a></section>}
 {error&&<section className="rounded-3xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</section>}</aside></div></div></main>
}
