"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";

export default function Home(){
 const router=useRouter();const[name,setName]=useState("");const[email,setEmail]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function start(){setLoading(true);setError("");try{const r=await fetch("/api/sessions/demo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:name,email})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Could not start session");router.push(`/call?session=${j.session.id}`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 return <main className="min-h-screen px-6 py-10"><div className="mx-auto max-w-4xl"><header className="mb-12 flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">INSURANOS</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Accident reporting without the typing.</h1></div><span className="rounded-full border bg-white px-3 py-1 text-xs text-slate-500">Voice-first FNOL</span></header><div className="grid gap-8 md:grid-cols-[1.3fr_0.7fr]"><section className="rounded-3xl bg-slate-900 p-8 text-white shadow-xl"><p className="max-w-xl text-lg leading-8 text-slate-200">A calm voice agent guides you through safety, incident details, vehicle damage, evidence, review and a ready-to-send claim report.</p><div className="mt-8 grid gap-3 text-sm text-slate-300 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4">1. Safety first</div><div className="rounded-2xl bg-white/10 p-4">2. One question at a time</div><div className="rounded-2xl bg-white/10 p-4">3. Structured claim data</div><div className="rounded-2xl bg-white/10 p-4">4. Report + next steps</div></div></section><section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-xl font-semibold">Start a demo claim</h2><p className="mt-2 text-sm text-slate-500">Enter these once. The rest is hands-free.</p><div className="mt-6 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" className="w-full rounded-xl border px-4 py-3 outline-none focus:ring-2 focus:ring-slate-200"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email for the report" className="w-full rounded-xl border px-4 py-3 outline-none focus:ring-2 focus:ring-slate-200"/>{error&&<p className="text-sm text-red-600">{error}</p>}<button onClick={start} disabled={loading||!name||!email} className="w-full rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{loading?"Starting…":"Start voice report"}</button></div><p className="mt-5 text-xs text-slate-400">Demo mode is enabled. OTP can be added later without changing the claim flow.</p></section></div></div></main>
}
