import { UNKNOWN_VALUE_SENTINEL, computeCompleteness, PhotoTypeEnum } from "@insuranos/schema";
import { IClaimRepository } from "../repository/IClaimRepository";
import { ClaimSession } from "../types";
import { buildReport } from "../report/buildReport";
import { renderClaimPdf } from "../report/renderPdf";
import { sendReportEmail } from "../report/sendEmail";
import { uploadPdf } from "../report/storage";
export interface ToolContext{repo:IClaimRepository;sessionId:string}
export interface ToolResult{ok:boolean;result:Record<string,unknown>;triggersPhaseCheck?:boolean}
const nz=<T>(v:T|undefined):T|null=>v===undefined?null:v;
export async function callTool(name:string,args:Record<string,any>,ctx:ToolContext):Promise<ToolResult>{switch(name){
case"record_safety_status":await ctx.repo.writeFieldGroup(ctx.sessionId,"safety",{injuries_reported:nz(args.injuries_reported),still_at_scene:nz(args.still_at_scene),injury_flag_note:nz(args.injury_flag_note)});if(args.injuries_reported===true){await ctx.repo.setRequiresFollowup(ctx.sessionId,true);await ctx.repo.logEvent(ctx.sessionId,"safety_escalation",{reason:"injuries_reported=true"})}return{ok:true,result:{recorded:"safety"},triggersPhaseCheck:true};
case"record_incident_basics":await ctx.repo.writeFieldGroup(ctx.sessionId,"incident",{date_time:nz(args.date_time),location:nz(args.location),description_summary:nz(args.description_summary),weather:nz(args.weather),road_conditions:nz(args.road_conditions),police_report_number:nz(args.police_report_number)});return{ok:true,result:{recorded:"incident"},triggersPhaseCheck:true};
case"record_other_party":await ctx.repo.writeFieldGroup(ctx.sessionId,"other_parties",[{name:nz(args.name),phone:nz(args.phone),insurer_name:nz(args.insurer_name),policy_number:nz(args.policy_number),vehicle:{make:nz(args.vehicle_make),model:nz(args.vehicle_model),plate:nz(args.vehicle_plate)}}]);return{ok:true,result:{recorded:"other_parties[0]"},triggersPhaseCheck:true};
case"record_vehicle_damage":await ctx.repo.writeFieldGroup(ctx.sessionId,"user_vehicle",{make:nz(args.make),model:nz(args.model),plate:nz(args.plate),damage_description:nz(args.damage_description),drivable:nz(args.drivable),airbags_deployed:nz(args.airbags_deployed)});return{ok:true,result:{recorded:"user_vehicle"},triggersPhaseCheck:true};
case"record_evidence":{const s=await mustSession(ctx);await ctx.repo.writeFieldGroup(ctx.sessionId,"evidence",{photos:s.claim_data.evidence.photos,witnesses:nz(args.witnesses),dashcam_available:nz(args.dashcam_available)});return{ok:true,result:{recorded:"evidence"},triggersPhaseCheck:true}}
case"record_policyholder_info":await ctx.repo.writeFieldGroup(ctx.sessionId,"policy_info",{policyholder_name:nz(args.policyholder_name),policy_number:nz(args.policy_number),contact_phone:nz(args.contact_phone),contact_email:nz(args.contact_email)});return{ok:true,result:{recorded:"policy_info"},triggersPhaseCheck:true};
case"request_photo_upload":{const pt=PhotoTypeEnum.safeParse(args.photo_type);return pt.success?{ok:true,result:{requested_photo_type:pt.data}}:{ok:false,result:{error:`invalid photo_type: ${args.photo_type}`}}}
case"mark_field_unknown":if(!args.field_path)return{ok:false,result:{error:"field_path is required"}};await ctx.repo.markFieldUnknown(ctx.sessionId,args.field_path);return{ok:true,result:{marked_unknown:args.field_path},triggersPhaseCheck:true};
case"get_field_completeness":{const s=await mustSession(ctx),c=computeCompleteness(s.claim_data);return{ok:true,result:{missing_required:c.missingRequired,flagged_gaps:c.flaggedGaps,is_report_eligible:c.isReportEligible,group_summary:c.groupSummary}}}
case"confirm_continue":return{ok:true,result:{continued:true},triggersPhaseCheck:true};
case"finish_evidence_capture":return{ok:true,result:{evidence_complete:true},triggersPhaseCheck:true};
case"confirm_claim_summary":return{ok:true,result:{confirmed:true},triggersPhaseCheck:true};
case"generate_report":{const s=await mustSession(ctx),c=computeCompleteness(s.claim_data);if(!c.isReportEligible)return{ok:false,result:{error:"required_fields_missing",missing_required:c.missingRequired},triggersPhaseCheck:true};const{report_json,summary_text}=buildReport(s.claim_data,c);await ctx.repo.createReportArtifact(ctx.sessionId,{report_json,summary_text,email_status:"pending"});try{const pdf=await renderClaimPdf(report_json),url=await uploadPdf(ctx.sessionId,pdf);await ctx.repo.updateReportArtifact(ctx.sessionId,{pdf_url:url})}catch(err){await ctx.repo.logEvent(ctx.sessionId,"tool_call",{tool:"generate_report",pdf_render_failed:String(err)})}return{ok:true,result:{generated:true,summary_text},triggersPhaseCheck:true}}
case"send_report_email":{const s=await mustSession(ctx),r=await ctx.repo.getReportArtifact(ctx.sessionId),email=s.claim_data.policy_info.contact_email;const to=typeof email==="string"&&email!==UNKNOWN_VALUE_SENTINEL?email:null;if(!r)return{ok:false,result:{error:"no report generated yet"}};if(!to)return{ok:false,result:{error:"no contact email on file"}};try{await sendReportEmail({to,pdfUrl:r.pdf_url,summaryText:r.summary_text??""});await ctx.repo.updateReportArtifact(ctx.sessionId,{emailed_to:to,emailed_at:new Date().toISOString(),email_status:"sent"});return{ok:true,result:{emailed_to:to}}}catch{await ctx.repo.updateReportArtifact(ctx.sessionId,{email_status:"failed"});return{ok:false,result:{error:"email_delivery_failed"}}}}
case"escalate_safety_concern":await ctx.repo.setRequiresFollowup(ctx.sessionId,true);await ctx.repo.logEvent(ctx.sessionId,"safety_escalation",{reason:args.reason??null});return{ok:true,result:{escalated:true}};
default:return{ok:false,result:{error:`unknown tool: ${name}`}}}}
async function mustSession(ctx:ToolContext):Promise<ClaimSession>{const s=await ctx.repo.getSession(ctx.sessionId);if(!s)throw new Error(`No ClaimSession ${ctx.sessionId}`);return s}
