import { UNKNOWN_VALUE_SENTINEL, computeCompleteness, PhotoTypeEnum } from "@insuranos/schema";
import { IClaimRepository } from "../repository/IClaimRepository";
import { ClaimSession } from "../types";
import { buildReport } from "../report/buildReport";
import { sendReportEmail } from "../report/sendEmail";
import { uploadPdf } from "../report/storage";
export interface ToolContext{repo:IClaimRepository;sessionId:string}
export interface ToolResult{ok:boolean;result:Record<string,unknown>;triggersPhaseCheck?:boolean}
const nz=<T>(v:T|undefined):T|null=>v===undefined?null:v;
function normalizeBool(v:unknown):boolean|null|string{if(v===true||v===false||v===UNKNOWN_VALUE_SENTINEL||v===null||v===undefined)return v??null;if(typeof v==="string"){const t=v.trim().toLowerCase();if(["yes","true","correct","yep","yeah"].includes(t))return true;if(["no","false","none","nope"].includes(t))return false}return v as string}
async function sendSms(to:string,summaryText:string){const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,from=process.env.TWILIO_FROM_NUMBER;if(!sid||!token||!from)return{configured:false,sid:null};const digits=to.trim().replace(/\D/g,"");const country=(process.env.TWILIO_DEFAULT_COUNTRY_CODE??"+91").replace(/\s/g,"");const normalized=to.trim().startsWith("+")?to.trim():(digits.startsWith(country.replace(/\D/g,""))?"+"+digits:country+digits);const auth=Buffer.from(sid+":"+token).toString("base64");const params=new URLSearchParams({To:normalized,From:from,Body:summaryText.length>1200?summaryText.slice(0,1197)+"...":summaryText});const r=await fetch(\`https://api.twilio.com/2010-04-01/Accounts/\${sid}/Messages.json\`,{method:"POST",headers:{"Authorization":\`Basic \${auth}\`,"Content-Type":"application/x-www-form-urlencoded"},body:params});if(!r.ok)throw new Error(\`twilio_http_\${r.status}\`);const j=await r.json() as {sid?:string};return{configured:true,sid:j.sid??null}}
export async function callTool(name:string,args:Record<string,any>,ctx:ToolContext):Promise<ToolResult>{switch(name){
case"record_safety_status":await ctx.repo.writeFieldGroup(ctx.sessionId,"safety",{injuries_reported:normalizeBool(args.injuries_reported) as any,still_at_scene:normalizeBool(args.still_at_scene) as any,injury_flag_note:nz(args.injury_flag_note)});if(args.injuries_reported===true){await ctx.repo.setRequiresFollowup(ctx.sessionId,true);await ctx.repo.logEvent(ctx.sessionId,"safety_escalation",{reason:"injuries_reported=true"})}return{ok:true,result:{recorded:"safety"},triggersPhaseCheck:true};
case"record_incident_basics":await ctx.repo.writeFieldGroup(ctx.sessionId,"incident",{date_time:nz(args.date_time),location:nz(args.location),description_summary:nz(args.description_summary),weather:nz(args.weather),road_conditions:nz(args.road_conditions),police_report_number:nz(args.police_report_number)});return{ok:true,result:{recorded:"incident"},triggersPhaseCheck:true};
case"record_other_party":await ctx.repo.writeFieldGroup(ctx.sessionId,"other_parties",[{name:nz(args.name),phone:nz(args.phone),insurer_name:nz(args.insurer_name),policy_number:nz(args.policy_number),vehicle:{make:nz(args.vehicle_make),model:nz(args.vehicle_model),plate:nz(args.vehicle_plate)}}]);return{ok:true,result:{recorded:"other_parties[0]"},triggersPhaseCheck:true};
case"record_vehicle_damage":await ctx.repo.writeFieldGroup(ctx.sessionId,"user_vehicle",{make:nz(args.make),model:nz(args.model),plate:nz(args.plate),damage_description:nz(args.damage_description),drivable:normalizeBool(args.drivable) as any,airbags_deployed:normalizeBool(args.airbags_deployed) as any});return{ok:true,result:{recorded:"user_vehicle"},triggersPhaseCheck:true};
case"record_evidence":{const s=await mustSession(ctx);await ctx.repo.writeFieldGroup(ctx.sessionId,"evidence",{photos:s.claim_data.evidence.photos,witnesses:nz(args.witnesses),dashcam_available:normalizeBool(args.dashcam_available) as any});return{ok:true,result:{recorded:"evidence"},triggersPhaseCheck:true}}
case"record_policyholder_info":await ctx.repo.writeFieldGroup(ctx.sessionId,"policy_info",{policyholder_name:nz(args.policyholder_name),policy_number:nz(args.policy_number),contact_phone:nz(args.contact_phone),contact_email:nz(args.contact_email)});return{ok:true,result:{recorded:"policy_info"},triggersPhaseCheck:true};
case"request_photo_upload":{const pt=PhotoTypeEnum.safeParse(args.photo_type);return pt.success?{ok:true,result:{requested_photo_type:pt.data}}:{ok:false,result:{error:\`invalid photo_type: \${args.photo_type}\`}}}
case"mark_field_unknown":if(!args.field_path)return{ok:false,result:{error:"field_path is required"}};await ctx.repo.markFieldUnknown(ctx.sessionId,args.field_path);return{ok:true,result:{marked_unknown:args.field_path},triggersPhaseCheck:true};
case"get_field_completeness":{const s=await mustSession(ctx),c=computeCompleteness(s.claim_data);return{ok:true,result:{missing_required:c.missingRequired,flagged_gaps:c.flaggedGaps,integrity_flags:c.integrityFlags,is_report_eligible:c.isReportEligible,group_summary:c.groupSummary}}}
case"confirm_continue":return{ok:true,result:{continued:true},triggersPhaseCheck:true};
case"finish_evidence_capture":return{ok:true,result:{evidence_complete:true},triggersPhaseCheck:true};
case"confirm_claim_summary":return{ok:true,result:{confirmed:true},triggersPhaseCheck:true};
case"generate_report":{const s=await mustSession(ctx),c=computeCompleteness(s.claim_data);if(!c.isReportEligible)return{ok:false,result:{error:"required_fields_missing",missing_required:c.missingRequired},triggersPhaseCheck:true};const{report_json,summary_text}=buildReport(s.claim_data,c);await ctx.repo.createReportArtifact(ctx.sessionId,{report_json,summary_text,email_status:"pending"});try{const { renderClaimPdf } = await import("../report/renderPdf");const pdf=await renderClaimPdf(report_json),url=await uploadPdf(ctx.sessionId,pdf);await ctx.repo.updateReportArtifact(ctx.sessionId,{pdf_url:url})}catch(err){await ctx.repo.logEvent(ctx.sessionId,"tool_call",{tool:"generate_report",pdf_render_failed:String(err)})}return{ok:true,result:{generated:true,summary_text},triggersPhaseCheck:true}}
case"send_report_sms":{const s=await mustSession(ctx),r=await ctx.repo.getReportArtifact(ctx.sessionId),phone=s.claim_data.policy_info.contact_phone;const to=typeof phone==="string"&&phone!==UNKNOWN_VALUE_SENTINEL?phone:null;if(!r)return{ok:false,result:{error:"no report generated yet"}};if(!to)return{ok:false,result:{error:"no contact phone on file"}};if(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!process.env.TWILIO_FROM_NUMBER)return{ok:true,result:{sent:false,skipped:true,reason:"twilio_not_configured"},triggersPhaseCheck:false};try{const sms=await sendSms(to,r.summary_text??"");return{ok:true,result:{sent:true,sid:sms.sid,to},triggersPhaseCheck:false}}catch{return{ok:false,result:{error:"sms_delivery_failed"},triggersPhaseCheck:false}}}
case"send_report_email":{const s=await mustSession(ctx),r=await ctx.repo.getReportArtifact(ctx.sessionId),email=s.claim_data.policy_info.contact_email;const to=typeof email==="string"&&email!==UNKNOWN_VALUE_SENTINEL?email:null;if(!r)return{ok:false,result:{error:"no report generated yet"}};if(!to)return{ok:false,result:{error:"no contact email on file"}};try{await sendReportEmail({to,pdfUrl:r.pdf_url,summaryText:r.summary_text??""});await ctx.repo.updateReportArtifact(ctx.sessionId,{emailed_to:to,emailed_at:new Date().toISOString(),email_status:"sent"});return{ok:true,result:{emailed_to:to}}}catch{await ctx.repo.updateReportArtifact(ctx.sessionId,{email_status:"failed"});return{ok:false,result:{error:"email_delivery_failed"}}}}
case"escalate_safety_concern":await ctx.repo.setRequiresFollowup(ctx.sessionId,true);await ctx.repo.logEvent(ctx.sessionId,"safety_escalation",{reason:args.reason??null});return{ok:true,result:{escalated:true}};
default:return{ok:false,result:{error:\`unknown tool: \${name}\`}}}}
async function mustSession(ctx:ToolContext):Promise<ClaimSession>{const s=await ctx.repo.getSession(ctx.sessionId);if(!s)throw new Error(\`No ClaimSession \${ctx.sessionId}\`);return s}
