import {Phase} from "../types";
export interface ToolDefinition{type:"function";name:string;description:string;parameters:{type:"object";properties:Record<string,unknown>;required?:string[]};phases:Phase[]|"all"}
const unknownableString={anyOf:[{type:"string"},{type:"null"}]};const unknownableBool={anyOf:[{type:"boolean"},{type:"null"}]};
export const TOOL_DEFINITIONS:ToolDefinition[]=[
{type:"function",name:"record_safety_status",description:"Record injury and scene safety status. Call as soon as you have an answer and again if it changes.",parameters:{type:"object",properties:{injuries_reported:unknownableBool,still_at_scene:unknownableBool,injury_flag_note:{type:"string",maxLength:280}}},phases:["opening_safety","grounding_consent","narrative","structured_gathering","evidence","review"]},
{type:"function",name:"record_incident_basics",description:"Record when and where the incident happened, a summary, weather, road conditions and police report number if known.",parameters:{type:"object",properties:{date_time:unknownableString,location:unknownableString,description_summary:{anyOf:[{type:"string",maxLength:2000},{type:"null"}]},weather:unknownableString,road_conditions:unknownableString,police_report_number:unknownableString}},phases:["narrative","structured_gathering"]},
{type:"function",name:"record_other_party",description:"Record the first other driver or party's name, phone, insurer, policy number and vehicle details when known.",parameters:{type:"object",properties:{name:unknownableString,phone:unknownableString,insurer_name:unknownableString,policy_number:unknownableString,vehicle_make:unknownableString,vehicle_model:unknownableString,vehicle_plate:unknownableString}},phases:["structured_gathering"]},
{type:"function",name:"record_vehicle_damage",description:"Record the caller's vehicle make, model, plate, damage and whether it is drivable.",parameters:{type:"object",properties:{make:unknownableString,model:unknownableString,plate:unknownableString,damage_description:unknownableString,drivable:unknownableBool,airbags_deployed:unknownableBool}},phases:["structured_gathering"]},
{type:"function",name:"record_evidence",description:"Record witness information and dashcam availability.",parameters:{type:"object",properties:{witnesses:unknownableString,dashcam_available:unknownableBool}},phases:["evidence"]},
{type:"function",name:"record_policyholder_info",description:"Record policyholder name, policy number and contact details.",parameters:{type:"object",properties:{policyholder_name:unknownableString,policy_number:unknownableString,contact_phone:unknownableString,contact_email:unknownableString}},phases:["structured_gathering","review"]},
{type:"function",name:"request_photo_upload",description:"Ask the caller to safely take and upload one specific photo. This only triggers the on-screen camera prompt; never assume it succeeded until told.",parameters:{type:"object",properties:{photo_type:{type:"string",enum:["plate","damage","scene","insurance_card"]}},required:["photo_type"]},phases:["evidence"]},
{type:"function",name:"mark_field_unknown",description:"Mark a genuinely unavailable requested field as unknown instead of looping or fabricating a value.",parameters:{type:"object",properties:{field_path:{type:"string"},reason:{type:"string"}},required:["field_path"]},phases:["opening_safety","narrative","structured_gathering","evidence","review"]},
{type:"function",name:"get_field_completeness",description:"Read the authoritative server-side completion state. Use it to decide what to ask next.",parameters:{type:"object",properties:{}},phases:"all"},
{type:"function",name:"confirm_continue",description:"Use after explicit consent to continue with the intake. The server advances the phase.",parameters:{type:"object",properties:{}},phases:["grounding_consent"]},
{type:"function",name:"finish_evidence_capture",description:"Use after evidence questions and safe photo requests are finished and the caller is ready to review. The server advances the phase.",parameters:{type:"object",properties:{}},phases:["evidence"]},
{type:"function",name:"confirm_claim_summary",description:"Use only after reading the complete claim summary and receiving explicit confirmation. The server advances to report generation.",parameters:{type:"object",properties:{}},phases:["review"]},
{type:"function",name:"generate_report",description:"Generate the insurer-ready report. Required fields must be filled or marked unknown.",parameters:{type:"object",properties:{}},phases:["output_generation"]},
{type:"function",name:"send_report_email",description:"Send the generated report and next steps to the caller's email.",parameters:{type:"object",properties:{}},phases:["output_generation"]},
{type:"function",name:"escalate_safety_concern",description:"Escalate possible injury or ongoing danger. This is available in every phase.",parameters:{type:"object",properties:{reason:{type:"string"}},required:["reason"]},phases:"all"}
];
export function toolsForPhase(phase:Phase){return TOOL_DEFINITIONS.filter(t=>t.phases==="all"||t.phases.includes(phase))}
export function toAssemblyAIToolSchema(defs:ToolDefinition[]){return defs.map(({type,name,description,parameters})=>({type,name,description,parameters}))}
